#!/bin/bash --posix
# https://api.gitstrapped.com/install-gitstrapped-2013032302
# (C) Asher Bond 2011-2013
# GitStrapped is a runtime bootstrapping utility for automated deployment of software application
# code atop a virtual or paravirtual machine or even a physical machine.. if that's what you're into.
# 
# GitStrapped also serves as the client of a Test-Driven-DevOps PaaS framework for distributed systems developers.
#
# Please read the License (AGPL v3)
# http://api.gitstrapped.com/LICENSE-AGPLv3.txt
# or
# https://www.gnu.org/licenses/agpl-3.0.de.html
# 
# To install @GitStrapped:
# curl -s -1 -k https://api.gitstrapped.com/install-gitstrapped | bash
#
# A STRAP is a Service Template Running A Process
# A STRAP may be licensed to you under similar or different terms.
# A STRAP may be licensed to the public under AGPLv3 or a more permissive license such as LGPL or BSD or GNU or Apache License.
# A user may invoke the STRAP at his or her own risk via gitstrapped <strap>
# This software is provided without Warranty.
#
# Please also join me in support of the Electronic Frontier Foundation (Defending Your Rights In The Digital World)
# https://www.eff.org/

gs_path='api.gitstrapped.com/gitstrapped-2013040401'
local_path='/usr/local/bin/gitstrapped'

if which curl | grep -q curl ; then
	curl -s -1 -k https://$gs_path > $local_path
elif which wget | grep -q wget ; then
	wget https://$gs_path --output-document=$local_path
fi

chmod 755 $local_path || ( echo "[FATALITY]: Couldn't download GitStrapped. Please download https://$gs_path to $local_path" && exit 1 )

$local_path $STRAP $OPTIONS

